### ISSUE TITLE
small request

### ISSUE THREAD

**Issue by ValeraGin** [elijahkash/libft#2]
Please add more descriptions for your library functions.

like that:

```
/*
**	Return a length a null-terminated string.
**	
**	@s - null-terminated string
*/
size_t			ft_strlen(const char *s);

```

**Comment by elijahkash** [comment]
Thanks!
I'm working under documentation and describing my lib just right now!
Be patient, and soon I'll finish)

**Comment by elijahkash** [comment]
done
Look at [wiki](https://github.com/elijahkash/libft/wiki)
