### ISSUE TITLE
[Feature Request] Будет ли русский вариант Wiki ?

### ISSUE THREAD

**Issue by ValeraGin** [elijahkash/libft#3]
**Москва, Казань, Киев ждут перевода))**

**Comment by elijahkash** [comment]
@ValeraGin нет, мной не планируется. 
1) язык технической документации в IT - английский.
2) любой будущий разработчик обязан знать английский
3) всегда есть google translate
4) старался писать не очень сложно, так что Вы должны разобраться

Если кто то из сообщества готов поработать над переводом и создать русский вариант вики, буду рад помочь.

Спасибо за участие!
